I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 835, in script
    martin sad "Интересно на что вы рассчитвали, когда тащились в такую даль даже не подготовившись..."
Exception: Image 'martin' does not accept attributes 'sad'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 835, in script
    martin sad "Интересно на что вы рассчитвали, когда тащились в такую даль даже не подготовившись..."
  File "C:\Users\Matthew\Downloads\renpy-8.1.3-sdk.7z\renpy-8.1.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Matthew\Downloads\renpy-8.1.3-sdk.7z\renpy-8.1.3-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "C:\Users\Matthew\Downloads\renpy-8.1.3-sdk.7z\renpy-8.1.3-sdk\renpy\character.py", line 1290, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "C:\Users\Matthew\Downloads\renpy-8.1.3-sdk.7z\renpy-8.1.3-sdk\renpy\character.py", line 1109, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "C:\Users\Matthew\Downloads\renpy-8.1.3-sdk.7z\renpy-8.1.3-sdk\renpy\character.py", line 1065, in resolve_say_attributes
    renpy.exports.show(show_image)
  File "C:\Users\Matthew\Downloads\renpy-8.1.3-sdk.7z\renpy-8.1.3-sdk\renpy\exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Matthew\Downloads\renpy-8.1.3-sdk.7z\renpy-8.1.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Matthew\Downloads\renpy-8.1.3-sdk.7z\renpy-8.1.3-sdk\renpy\display\core.py", line 499, in _duplicate
    args.extraneous()
  File "C:\Users\Matthew\Downloads\renpy-8.1.3-sdk.7z\renpy-8.1.3-sdk\renpy\display\core.py", line 362, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'martin' does not accept attributes 'sad'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
NOVEL 1.0
Sun Dec 31 00:52:36 2023
